### ISSUE TITLE
Book Clear isn't working - neither is Copying/Pasting anything into a book

### ISSUE THREAD

**Issue by KiwiParis** [ThroneCraft/issues#24]
**Describe the bug**
To be simple, any of the previous /book commands we had access too, we no longer have this include: /book clear, /book author, /book title, /book unlock

Another side thing is allowing coloured books, previously in 1.12.2 I used to make books with italics and coloured text - just to add a bit of immersion, when attempting to try this in 1.15.2, the Copy/Paste didn't seem to work, when I can add text just fine.
The part I'm trying to copy is: §. Upon me doing this, it didn't show up nor could I add any colours/italics, unsure if this now requires a permission or if minecraft has removed/changed it all together. 
 
**Expected behaviour**
Self-explanatory for the commands. /book clear, clears the book and gives an unopened book and quill. /book author allows you to change the "by KiwiParis" to something else. ./book title, allows you to make a longer title with colours. /book unlock allows you to unlock a book and continue editing.

Normally when pasting § symbol into a book, it comes up with white text that behaves as if used with k, then upon putting a code (refer to formatting codes for books), if you write §o - §o will no longer be in the book, instead, you'd be writing in italics.

**Screenshots**
For the /book commands not working (all of them came up with this):
[https://gyazo.com/665acff7d31986f7a0ef7819864de0b8](url)

For the pasting formatting symbol (in a online note pad):
[https://gyazo.com/168faa96ac0c47265dfb8618c570b38a](url)

For the pasting formatting symbol (in a minecraft book - default textures):
[https://gyazo.com/254af61c9d7330a37da86e2c6191b6db](url)

***Minecraft username:***
Your Minecraft username.
KiwiParis

**Comment by jvdoorn** [comment]
You are not able to use`§` because of the new Minecraft version, Mojang decided to remove this feature. To bypass this we have installed a plugin, you should now be able to use `&` to format books (and their title). Note that the colours will only take effect after signing the book. 

To reopen a book after signing simply do `/book` or `/sr book unSign`, to change the Author use `/book author` or `/sr book setAuthor` to change the title we recommend using `/sr book setTitle` over `/book title` as the first on support colour codes using `&` sign.

This issue will be regarded as solved if any problems persist please reopen this issue.

**Comment by KiwiParis** [comment]
This still doesn't work. I tried to commands you put before and it either says:
[This](https://gyazo.com/ca07484a64520da155f3f3c54fd2d2b1)
Or 
[This](https://gyazo.com/9a9f941d45486aae2bec4c5999f06cca)
