### ISSUE TITLE
Brewery not working properly?

### ISSUE THREAD

**Issue by arbiterthedog** [ThroneCraft/issues#33]
**Describe the bug**
When using brewery to boil a mix, two items that I have tried out have not been allowed in the cauldron for whatever reason. I was attempting to make blueberry wine first but it would not let me put Lapiz in it, and then when I tried rose wine, it would not let me use rose bushes to put on it. 
**Expected behaviour**
What I expected to happen is to be able to drop those items into the cauldron to begin brewing the drinks, but when I right click, it didn't go into the cauldron nor did it consume it.

***Minecraft username:***
ArbiterRequiem

**Comment by jvdoorn** [comment]
Possibly related to #29 .

**Comment by FInnJp** [comment]
Even if you could put those items into the cauldron, from what I can see no brewery drink uses those ingredients. Although, Lapis Ore is used, so if a recipe has "Lapis" in it, it most likely means Lapis Ore then

**Comment by FInnJp** [comment]
So after taking an extensive look into the matter, for some reason, even since Karuta, lapis itself could not be put into drinks, but lapis ore could(I assume because it counts as color, and most if not all color items cannot be used for drinks anymore). Regarding the Rose Wine, that does not seem to be a problem anymore as you should be able to put rose bushes into cauldrons. And trying to drop ingredients into the cauldron has never worked, it must be right-clicked into it. Do contact me if the rose bush thing does not still work for you for some reason.

Otherwise, I believe this issue should be solved as I see no other problems that still linger with it.
