### ISSUE TITLE
Make age not displayed publicly.

### ISSUE THREAD

**Issue by TheAquaLord** [ThroneCraft/issues#55]
**Is your feature request related to a problem? Please describe.**
Not everyone wants their age publicly shown.

**Describe the solution you'd like**
An option to toggle the visibility of it altogether 

**Describe alternatives you've considered**
Could also just state that it's unknown.

**Additional context**
na

***Minecraft username:***
TheAquaLord

**Comment by Brsssh** [comment]
For this maybe make it so it displays how old they appear not necessarily their exact age unless they’re considered a child. For example my character currently appears 21, and since people would be able to see that I don’t have any issue with them knowing, but in reality since she’s an elf she’s much older. Most people that don’t want their exact ages known will just give the age the character appears, but you could make it required for children characters to put their exact age

**Comment by Benlier** [comment]
I think Brsssh describes this well. Only children characters (16-) are required to have their actual age in order for their adjusted stats to be incorporated in their rolls. Older characters may enter an age value of how old they appear to be
